language: java
sudo: required
jdk:
- oraclejdk8

before_install:
  - mvn clean -q
  - cp mathosphere.properties mathosphere-core/src/main/resources/

install:
  - mvn install -DskipTests=true -q

script:
   - mvn test -q -fae -Dlog4j.configurationFile="$TRAVIS_BUILD_DIR/mathosphere-core/src/main/resources/log4j2-travis.xml"

after_success:
  - mvn jacoco:report coveralls:report -Dlog4j.configurationFile="$TRAVIS_BUILD_DIR/mathosphere-core/src/main/resources/log4j2-travis.xml"

before_script:
  - sudo apt-get install -y nodejs librsvg2-dev
  - npm i mathoid
  - cd node_modules/mathoid
  - ./server.js -c ../../config.dev.yaml &
  - cd ../..

cache:
  directories:
  - $HOME/.m2